#!/bin/sh

echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@" // saraksts no argumentiem
echo "Quoted Values: $*" // visi kaa viens arguments
echo "Total Number of Parameters : $#"
